version: '3'
services:
  todofront:
    build: ./todo-app/front-end
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    restart: always

  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    restart: always

  todotests:
    build: ./todo-app/tests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    restart: always

