version: '3'
services:
  todofront:
    build: front-end/
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=backend
    networks:
      - rede-virtual-1

  todoback:
    build: back-end/
    ports:
      - 3001:3001
    networks:
      - rede-virtual-1

  todotests:
    build: tests/
    environment:
      - FRONT_HOST=frontend
    networks:
      - rede-virtual-1
    depends_on:
      - todofront
      - todoback


networks:
  rede-virtual-1:
